# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: subscriptions-dashboard-ui
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: subscriptions-dashboard-ui
    spec:
      envName: ${ENV_NAME}
      title: Subscriptions Dashboard
      feoConfigEnabled: true
      deploymentRepo: https://github.com/RedHatInsights/subscriptions-dashboard-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/subscriptions-dashboard-ui
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/subscriptions-dashboard-ui/fed-mods.json'
        defaultDocumentTitle: Subscription Dashboard | Subscription Dashboard
        modules:
          - id: subscriptions-dashboard-ui
            module: './RootApp'
            routes:
              - pathname: /subscriptions
              - pathname: /subscriptions/overview
        bundleSegments:
        - segmentId: subscriptions-dashboard-ui
          bundleId: subscriptions
          navItems:
            - title: Overview
              id: overview
              href: "/subscriptions/overview"
              icon: SubscriptionsIcon
          position: 300

        searchEntries:
        - id: subscriptions-dashboard-ui
          title: Subscriptions Dashboard
          href: "/subscriptions/overview"

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/subscriptions-dashboard-ui
